# Generated by Django 2.2.5 on 2019-09-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing1',
            name='marks',
            field=models.CharField(max_length=50),
        ),
    ]
