# Generated by Django 2.2.5 on 2019-09-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190917_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='mark',
            field=models.IntegerField(default=11),
        ),
    ]
