# Generated by Django 2.2.5 on 2019-09-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_destination_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
