# Generated by Django 2.2.5 on 2019-09-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_testing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testing',
            new_name='testing1',
        ),
    ]
