# Generated by Django 2.2.5 on 2019-09-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190918_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing1',
            name='marks',
        ),
        migrations.AddField(
            model_name='testing1',
            name='blood',
            field=models.CharField(default='O Positive', max_length=20),
        ),
        migrations.AddField(
            model_name='testing1',
            name='city',
            field=models.CharField(default='some city   ', max_length=20),
        ),
        migrations.AddField(
            model_name='testing1',
            name='country',
            field=models.CharField(default='some country', max_length=20),
        ),
        migrations.AddField(
            model_name='testing1',
            name='dob',
            field=models.DateField(default='2019-11-11'),
        ),
        migrations.AddField(
            model_name='testing1',
            name='donor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testing1',
            name='email',
            field=models.EmailField(default='aa@ddd', max_length=254),
        ),
        migrations.AddField(
            model_name='testing1',
            name='mobile',
            field=models.BigIntegerField(default=123),
        ),
        migrations.AddField(
            model_name='testing1',
            name='state',
            field=models.CharField(default='some state', max_length=20),
        ),
    ]
