# Generated by Django 2.2.5 on 2019-09-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190918_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing1',
            name='agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testing1',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
