# Generated by Django 2.2.5 on 2019-09-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190918_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganDonors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField(default='2019-11-11')),
                ('blood', models.CharField(default='O Positive', max_length=20)),
                ('mobile', models.BigIntegerField(default=123)),
                ('email', models.EmailField(default='aa@ddd', max_length=254)),
                ('country', models.CharField(default='some country', max_length=20)),
                ('donortype', models.CharField(max_length=20)),
                ('organs1', models.CharField(max_length=20)),
                ('organs2', models.CharField(max_length=20)),
                ('state', models.CharField(default='some state', max_length=20)),
                ('city', models.CharField(default='some city   ', max_length=20)),
                ('agree', models.BooleanField(default=False)),
            ],
        ),
    ]
