# Generated by Django 2.2.5 on 2019-09-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organdonors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organdonors',
            name='mobile',
        ),
    ]
