# Generated by Django 2.2.5 on 2019-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_organdonors_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organdonors',
            name='mobile',
            field=models.BigIntegerField(default=123),
        ),
    ]
