# Generated by Django 2.2.5 on 2019-09-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190921_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organdonors',
            name='organs2',
        ),
    ]
