# Generated by Django 2.2.5 on 2019-09-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_organdonors_organs2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organdonors',
            name='agree',
            field=models.CharField(default='agree', max_length=20),
        ),
    ]
