# Generated by Django 2.2.5 on 2019-09-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190922_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organdonors',
            name='blood',
            field=models.CharField(default='O Positive', max_length=200),
        ),
        migrations.AlterField(
            model_name='organdonors',
            name='city',
            field=models.CharField(default='some city   ', max_length=200),
        ),
        migrations.AlterField(
            model_name='organdonors',
            name='country',
            field=models.CharField(default='some country', max_length=200),
        ),
        migrations.AlterField(
            model_name='organdonors',
            name='donortype',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organdonors',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organdonors',
            name='organs1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organdonors',
            name='state',
            field=models.CharField(default='some state', max_length=200),
        ),
    ]
