# Generated by Django 2.2.5 on 2019-09-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_hostuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostuser',
            old_name='password1',
            new_name='password',
        ),
    ]
