# Generated by Django 2.2.5 on 2019-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20190919_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcamp',
            name='state',
            field=models.CharField(default='some state', max_length=40),
        ),
    ]
