# Generated by Django 2.2.5 on 2019-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_auto_20190919_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcamp',
            name='blood',
            field=models.TextField(default='Any address', max_length=100),
        ),
    ]
