# Generated by Django 2.2.5 on 2019-09-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_auto_20190919_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcamp',
            name='emergency',
            field=models.TextField(default=100),
        ),
    ]
