# Generated by Django 2.2.5 on 2019-09-19 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_auto_20190919_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostcamp',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
    ]
