# Generated by Django 2.2.5 on 2019-09-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0008_auto_20190919_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcamp',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
