# Generated by Django 2.2.5 on 2019-09-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0011_auto_20190919_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcamp',
            name='image',
            field=models.FileField(upload_to='pics/'),
        ),
    ]
