# Generated by Django 2.2.5 on 2019-09-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0013_auto_20190919_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostcamp',
            name='image',
        ),
    ]
